CREATE TABLE order ( order_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY, customer_id INTEGER NOT NULL, CONSTRAINT order_cust_fk FOREIGN KEY (customer_num) REFERENCES customer (customer_num))
CREATE TABLE customer ( customer_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY, last_name VARCHAR(255), first_name VARCHAR(255), email VARCHAR(255))
SELECT username FROM users
SELECT * FROM customer WHERE (customer_id BETWEEN ? AND ?) AND last_name LIKE ?
CREATE TABLE order_items ( order_id INTEGER NOT NULL, product_number VARCHAR(64), item_count INTEGER NOT NULL, CONSTRAINT item_order_fk FOREIGN KEY (order_id) REFERENCES order (order_id), CONSTRAINT item_product_fk FOREIGN KEY (product_key) REFERENCES product (product_key))
SELECT COUNT(*) FROM users WHERE username LIKE ?
CREATE TABLE product ( product_number VARCHAR(64), description VARCHAR(255), weight_grams DECIMAL(7,2))
SELECT * FROM customer
SELECT count(id) FROM target_class1
