SELECT sessiontimezone FROM dual
SELECT ad_description FROM widgets WHERE ad_description = ?
SELECT id FROM widgets WHERE id = ?
UPDATE users SET name = ?  WHERE id = 900
SELECT 1 FROM dual
SELECT code FROM widgets WHERE ad_description = ?
SELECT flags FROM widgets WHERE ad_description = ?
SELECT name FROM users WHERE name = #{@n}\'#{name}\'
CREATE TABLE `widgets` ( `id` int(11) NOT NULL auto_increment, `code` char(8) default 'A14' NULL, `name` varchar(200) default 'Super Widget' NULL, `shelf_location` tinytext NULL, `description` text NULL, `image_data` blob NULL, `ad_description` mediumtext NULL, `ad_image` mediumblob NULL, `whitepaper_text` longtext NULL, `cad_drawing` longblob NULL, `flags` boolean default false, `number_in_stock` smallint default 500, `number_sold` mediumint default 0, `super_number` bigint default 9223372036854775807, `weight` float default 1.23, `cost1` double default 10.23, `cost2` decimal(8,2) default 50.23, `release_date` date default '2008-02-14', `release_datetime` datetime default '2008-02-14 00:31:12', `release_timestamp` timestamp NULL default '2008-02-14 00:31:31', `status` enum('active','out of stock') NOT NULL default 'active', PRIMARY KEY (`id`) )
SELECT cost1 FROM widgets WHERE ad_description = ?
SELECT ad_description FROM widgets WHERE cad_drawing = ?").execute_reader(::Extlib::ByteArray.new("CAD \001 \000 DRAWING
SELECT number_sold FROM widgets WHERE ad_description = ?
SELECT * FROM zoos WHERE name = ? AND acreage > ?", "Dallas
SELECT release_datetime FROM widgets WHERE id = ? OR id = ? ORDER BY id
UPDATE widgets SET super_number = ?  WHERE id = 10
SELECT whitepaper_text FROM widgets WHERE whitepaper_text = ?
CREATE TABLE users ( id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, name VARCHAR(200) default 'Billy', fired_at TIMESTAMP )
SELECT * FROM zoos
SELECT release_date FROM widgets WHERE ad_description = ?
CREATE TABLE invoices ( id BIGINT PRIMARY KEY DEFAULT -1, invoice_number VARCHAR(50) NOT NULL )
SELECT * FROM non_existent_widgets WHERE ad_description = ? AND white_paper_text = ?
CREATE TABLE users ( id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1), name VARCHAR(200) default 'Billy' NULL, fired_at TIMESTAMP )
CREATE TABLE `invoices` ( `invoice_number` varchar(50) NOT NULL, PRIMARY KEY (`invoice_number`) )
CREATE TABLE users ( id INTEGER IDENTITY, name VARCHAR(200) default 'Billy' NULL, fired_at TIMESTAMP )
SELECT cad_drawing FROM widgets WHERE ad_description = ?
SELECT class_name FROM widgets WHERE ad_description = ?
SELECT id FROM widgets WHERE release_date = ? ORDER BY id
SELECT weight FROM widgets WHERE ad_description = ?
SELECT * FROM widgets WHERE id in ?
SELECT name, whitepaper_text FROM widgets WHERE ad_description = ?
SELECT whitepaper_text FROM widgets WHERE id = ?
SELECT * FROM zoos WHERE name = ?", "Dallas
SELECT ad_description FROM widgets WHERE id = ?
CREATE TABLE `users` ( `id` int(11) NOT NULL auto_increment, `name` varchar(200) default 'Billy' NULL, `fired_at` timestamp, PRIMARY KEY (`id`) )
SELECT cad_drawing FROM widgets WHERE id = ?
SELECT id FROM widgets WHERE ad_description IN (?) ORDER BY id
SELECT cost2 FROM widgets WHERE id = ?
SELECT * FROM widgets WHERE id between ?
CREATE TABLE users ( id NUMBER(38,0) PRIMARY KEY NOT NULL, name VARCHAR(200) default 'Billy', fired_at timestamp )
SELECT code, name FROM widgets WHERE ad_description = ?
update widgets set release_timestamp = ?  where id = 1
SELECT 1 FROM SYSIBM.SYSDUMMY1
SELECT release_date FROM widgets WHERE id = ?
update widgets set flags = true  where id = 2
SELECT code, name FROM widgets WHERE ad_description = ? AND whitepaper_text = ?
SELECT id FROM widgets WHERE id = ?").execute_reader(::StringWithExtraPowers.new("2
CREATE TABLE `stuff` ( `id` bigint NOT NULL auto_increment, `value` varchar(50) NULL, PRIMARY KEY (`id`) )
SELECT release_date FROM widgets WHERE release_date = '0001-01-01'
SELECT cost1 FROM widgets WHERE id = ?
SELECT class_name FROM widgets WHERE class_name = ?
SELECT name FROM users_mb4
SELECT id FROM widgets WHERE ad_description = ?
SELECT release_datetime FROM widgets WHERE release_datetime = '0000-00-00 00:00:00'
SELECT release_datetime FROM widgets WHERE ad_description = ?
SELECT cost2 FROM widgets WHERE ad_description = ?
SELECT super_number FROM widgets WHERE id = ?
SELECT id FROM widgets WHERE id = ?").execute_reader(::Extlib::ByteArray.new("2
SELECT code, name FROM widgets WHERE ad_description = ? order by id
SELECT release_timestamp FROM widgets WHERE id < ? order by id
SELECT release_datetime FROM widgets WHERE id = ?
SELECT code FROM widgets WHERE ad_description = ? order by id
SELECT id FROM widgets WHERE flags = ?
select * from master..syslanguages
SELECT * FROM zoos WHERE name = `Dallas` AND acreage > 40
CREATE TABLE users ( id BIGINT PRIMARY KEY DEFAULT -1, name VARCHAR(200) default 'Billy', fired_at TIMESTAMP )
select 1 from INFORMATION_SCHEMA.SYSTEM_USERS
SELECT SIGN(1) FROM SYSPROGRESS.SYSCALCTABLE
CREATE TABLE widgets ( id BIGINT PRIMARY KEY DEFAULT -1, code CHAR(8) DEFAULT 'A14', name VARCHAR(200) DEFAULT 'Super Widget', shelf_location VARCHAR(4000), description VARCHAR(4000), image_data BLOB, ad_description VARCHAR(4000), ad_image BLOB, whitepaper_text CLOB, class_name VARCHAR(4000), cad_drawing BLOB, flags BIT DEFAULT 0, number_in_stock SMALLINT DEFAULT 500, number_sold INTEGER DEFAULT 0, super_number BIGINT DEFAULT 9223372036854775807, weight FLOAT DEFAULT 1.23, cost1 REAL DEFAULT 10.23, cost2 DECIMAL DEFAULT 50.23, release_date DATE DEFAULT '2008-02-14', release_datetime TIMESTAMP DEFAULT '2008-02-14 00:31:12', release_timestamp TIMESTAMP DEFAULT '2008-02-14 00:31:31' )
SELECT id FROM widgets WHERE id = ?").execute_reader(BigDecimal("2.0
SELECT id FROM widgets WHERE release_datetime = ? ORDER BY id
SELECT weight, cost1 FROM widgets WHERE ad_description = ?
SELECT * FROM zoos WHERE name = `Dallas`
CREATE TABLE `users_mb4` ( `id` int(11) NOT NULL auto_increment, `name` varchar(200), PRIMARY KEY (`id`) )
SELECT release_timestamp FROM widgets WHERE id = ?
SELECT flags FROM widgets WHERE id = ?
SELECT name FROM users WHERE id = 900
CREATE TABLE invoices ( id NUMBER(38,0) PRIMARY KEY NOT NULL, invoice_number VARCHAR2(50) NOT NULL )
SELECT whitepaper_text FROM widgets WHERE ad_description = ?
SELECT release_date FROM widgets WHERE release_date = '0000-00-00'
SELECT id FROM widgets WHERE id = ?").execute_reader("2
SELECT ad_image FROM widgets WHERE ad_description = ?
