SELECT f1,f2 FROM t1 WHERE f1=2 ORDER BY order desc) ORDER BY f1";
SELECT f1,f2 FROM t1 ORDER BY f2
SELECT f1,f2 FROM t1
SELECT * FROM (SELECT goja_ptbs.*,ROWNUM num FROM (%s) goja_ptbs WHERE ROWNUM <= ? ) WHERE num >= ?
SELECT f1,f2 FROM t1 LEFT JOIN t1=t2
SELECT f1,f2 FROM t1 INNER JOIN t1=t2
SELECT f1,f2 FROM t1 LIMIT 10
SELECT f1,f2 FROM t1 GROUP BY f2
SELECT f1,f2 FROM t1 WHERE f1 = ?
SELECT f1,f2 FROM t1 WHERE f1=2 ORDER BY order desc) UNION (SELECT f1,f2 FROM t2 WHERE f2=2 ORDER BY order desc) ORDER BY f1";
SELECT 1 FROM dual
create table ss_user (	id bigint generated by default as identity,	login_name varchar(64) not null unique,	name varchar(64) not null,	password varchar(255) not null,	salt varchar(64) not null,	roles varchar(255) not null,	register_date timestamp not null,	primary key (id))
SELECT f1,f2 FROM t1 WHERE f1=1 AND f2=?
SELECT f1,f2 FROM t1 WHERE f1=1 OR f2=?
SELECT f1,f2 FROM t1 WHERE f1=2 ORDER BY order desc) UNION ALL (SELECT f1,f2 FROM t2 WHERE f2=2 ORDER BY order desc)";
SELECT f1,f2 FROM t1 WHERE f1=2 ORDER BY order desc) LIMIT 10";
SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS
create table ss_task (	id bigint generated by default as identity,	title varchar(128) not null,	description varchar(255),	user_id bigint not null, primary key (id))
SELECT f1,f2 FROM t1 WHERE f1 IN (1, 2, 3)
SELECT f1,f2 FROM t1 WHERE f1=1
SELECT 1 FROM sysibm.sysdummy1
