SELECT _testEntity FROM TestEntity _testEntity
select * from EMPLOYEE_NATIVE_SQL
update Child set children_id = 1, children_ORDER = 0  where id = 1
SELECT m FROM Movie m
SELECT m FROM Movie m WHERE m.id IN :movieIds
create table Child ( * id bigint generated by default as identity, * parent_id bigint, * children_ORDER integer, * * primary key (id), * foreign key (parent_id) references Parent * )
SELECT c FROM Person c WHERE c.name = :name
create table Child ( * id bigint generated by default as identity, * children_id bigint, * children_ORDER integer, * * primary key (id), * foreign key (children_id) references Parent * )
SELECT c FROM Person c
SELECT p FROM ProductCode p WHERE p.prodCode = :prodCode
update Child set children_id = 1, children_ORDER = 0  where id = 1
SELECT m FROM Movie m WHERE m.actors = :actors
select * from EMPLOYEE_NATIVE_SQL_RESULTSET_MAPPING", "myMapping
SELECT p FROM ProductCode p
SELECT m FROM Movie m WHERE m.id = :movieId
SELECT e FROM Employee e
SELECT p FROM ProductCode p WHERE p.discountCode = :discountCode
update Child set children_ORDER = 0  where id = 1
SELECT m FROM Movie m WHERE m.name = :name
SELECT c FROM Person c WHERE c.hiredate = :hiredate
create table Parent ( * id bigint generated by default as identity, * * primary key (id) * )
SELECT r FROM Rating r WHERE r.name = :name
SELECT * FROM test.person
SELECT p FROM ProductCode p WHERE p.description = :description
update Child set parent_id = 1, children_ORDER = 0  where id = 1
update Child set children_id = 1, children_ORDER = 0  where id = 1
SELECT m FROM Movie m WHERE m.id = :id
SELECT c FROM Character c
