CREATE TABLE claim_issuer ( owner_id NUMBER(19) NOT NULL, issuer VARCHAR2(1024) NOT NULL)
CREATE TABLE IF NOT EXISTS blacklisted_site (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	uri VARCHAR(2048))
CREATE TABLE client_response_type ( owner_id NUMBER(19), response_type VARCHAR2(2000))
CREATE TABLE IF NOT EXISTS pairwise_identifier (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	identifier VARCHAR(256),	sub VARCHAR(256),	sector_identifier VARCHAR(2048))
CREATE TABLE access_token ( id NUMBER(19) NOT NULL PRIMARY KEY, token_value VARCHAR2(4000), expiration TIMESTAMP, token_type VARCHAR2(256), refresh_token_id NUMBER(19), client_id NUMBER(19), auth_holder_id NUMBER(19), id_token_id NUMBER(19), approved_site_id NUMBER(19))
CREATE TABLE client_resource ( owner_id NUMBER(19), resource_id VARCHAR2(256))
CREATE TABLE IF NOT EXISTS authentication_holder_scope (	owner_id BIGINT,	scope VARCHAR(2048))
CREATE INDEX rf_ahi_idx ON refresh_token(auth_holder_id);
CREATE TABLE IF NOT EXISTS access_token (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	token_value VARCHAR(4096),	expiration TIMESTAMP,	token_type VARCHAR(256),	refresh_token_id BIGINT,	client_id BIGINT,	auth_holder_id BIGINT,	id_token_id BIGINT,	approved_site_id BIGINT)
select a from ApprovedSite a where a.clientId = :
CREATE TABLE pairwise_identifier ( id NUMBER(19) NOT NULL PRIMARY KEY, identifier VARCHAR2(256), sub VARCHAR2(256), sector_identifier VARCHAR2(2048))
select b from BlacklistedSite b
CREATE TABLE IF NOT EXISTS whitelisted_site (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	creator_user_id VARCHAR(256),	client_id VARCHAR(256))
CREATE TABLE client_contact ( owner_id NUMBER(19), contact VARCHAR2(256))
CREATE TABLE IF NOT EXISTS approved_site (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	user_id VARCHAR(256),	client_id VARCHAR(256),	creation_date TIMESTAMP,	access_date TIMESTAMP,	timeout_date TIMESTAMP,	whitelisted_site_id BIGINT)
CREATE TABLE resource_set_scope ( owner_id NUMBER(19) NOT NULL, scope VARCHAR2(256) NOT NULL)
CREATE TABLE IF NOT EXISTS claim (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	name VARCHAR(256),	friendly_name VARCHAR(1024),	claim_type VARCHAR(1024),	claim_value VARCHAR(1024))
CREATE TABLE client_redirect_uri ( owner_id NUMBER(19), redirect_uri VARCHAR2(2048))
select a from AuthenticationHolderEntity a where 
CREATE TABLE IF NOT EXISTS saved_user_auth_authority (	owner_id BIGINT,	authority VARCHAR(256))
CREATE TABLE IF NOT EXISTS approved_site (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	user_id VARCHAR(256),	client_id VARCHAR(256),	creation_date TIMESTAMP NULL,	access_date TIMESTAMP NULL,	timeout_date TIMESTAMP NULL,	whitelisted_site_id BIGINT)
CREATE TABLE IF NOT EXISTS saved_user_auth (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	name VARCHAR(1024),	authenticated BOOLEAN,	source_class VARCHAR(2048))
select r from ResourceSet r where r.owner = :" + ResourceSet.PARAM_OWNER + " and r.clientId = :
select a from AuthorizationCodeEntity a where a.expiration <= :
select r from OAuth2RefreshTokenEntity r where r.client = :
CREATE INDEX at_exp_idx ON access_token(expiration);
CREATE TABLE IF NOT EXISTS policy (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	name VARCHAR(1024),	resource_set_id BIGINT)
select s from SystemScope s ORDER BY s.id
CREATE TABLE system_scope ( id NUMBER(19) NOT NULL PRIMARY KEY, scope VARCHAR2(256) NOT NULL, description VARCHAR2(4000), icon VARCHAR2(256), restricted NUMBER(1) DEFAULT 0 NOT NULL, default_scope NUMBER(1) DEFAULT 0 NOT NULL, structured NUMBER(1) DEFAULT 0 NOT NULL, structured_param_description VARCHAR2(256), CONSTRAINT system_scope_unique UNIQUE (scope), CONSTRAINT default_scope_check CHECK (default_scope in (1,0)), CONSTRAINT restricted_check CHECK (restricted in (1,0)), CONSTRAINT structured_check CHECK (structured in (1,0)))
CREATE TABLE policy_scope ( owner_id NUMBER(19) NOT NULL, scope VARCHAR2(256) NOT NULL)
CREATE TABLE IF NOT EXISTS authentication_holder_resource_id (	owner_id BIGINT,	resource_id VARCHAR(2048))
CREATE TABLE IF NOT EXISTS client_claims_redirect_uri (	owner_id BIGINT, 	redirect_uri VARCHAR(2048) )
select p from PermissionTicket p where p.ticket = :
CREATE TABLE IF NOT EXISTS resource_set (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	name VARCHAR(1024) NOT NULL,	uri VARCHAR(1024),	icon_uri VARCHAR(1024),	rs_type VARCHAR(256),	owner VARCHAR(256) NOT NULL,	client_id VARCHAR(256))
CREATE TABLE IF NOT EXISTS saved_registered_client (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	issuer VARCHAR(1024),	registered_client VARCHAR(8192))
select a from OAuth2AccessTokenEntity a where a.jwt = :
CREATE TABLE IF NOT EXISTS saved_registered_client (	id SERIAL PRIMARY KEY,	issuer VARCHAR(1024),	registered_client VARCHAR(8192))
CREATE TABLE IF NOT EXISTS blacklisted_site (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	uri VARCHAR(2048))
CREATE TABLE IF NOT EXISTS user_info (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	sub VARCHAR(256),	preferred_username VARCHAR(256),	name VARCHAR(256),	given_name VARCHAR(256),	family_name VARCHAR(256),	middle_name VARCHAR(256),	nickname VARCHAR(256),	profile VARCHAR(256),	picture VARCHAR(256),	website VARCHAR(256),	email VARCHAR(256),	email_verified BOOLEAN,	gender VARCHAR(256),	zone_info VARCHAR(256),	locale VARCHAR(256),	phone_number VARCHAR(256),	phone_number_verified BOOLEAN,	address_id VARCHAR(256),	updated_time VARCHAR(256),	birthdate VARCHAR(256),	src VARCHAR(4096))
CREATE TABLE IF NOT EXISTS system_scope (	id SERIAL PRIMARY KEY,	scope VARCHAR(256) NOT NULL,	description VARCHAR(4096),	icon VARCHAR(256),	restricted BOOLEAN DEFAULT false NOT NULL,	default_scope BOOLEAN DEFAULT false NOT NULL,	structured BOOLEAN DEFAULT false NOT NULL,	structured_param_description VARCHAR(256),	UNIQUE (scope))
CREATE TABLE IF NOT EXISTS authorization_code (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	code VARCHAR(256),	auth_holder_id BIGINT,	expiration TIMESTAMP)
CREATE TABLE blacklisted_site ( id NUMBER(19) NOT NULL PRIMARY KEY, uri VARCHAR2(2048))
select u from DefaultUserInfo u WHERE u.email = :
CREATE TABLE IF NOT EXISTS client_post_logout_redirect_uri (	owner_id BIGINT,	post_logout_redirect_uri VARCHAR(2000))
CREATE TABLE IF NOT EXISTS permission_ticket (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	ticket VARCHAR(256) NOT NULL,	permission_id BIGINT NOT NULL,	expiration TIMESTAMP NULL)
select a from OAuth2AccessTokenEntity a where a.refreshToken = :
CREATE TABLE IF NOT EXISTS policy_scope (	owner_id BIGINT NOT NULL,	scope VARCHAR(256) NOT NULL)
CREATE TABLE authentication_holder ( id NUMBER(19) NOT NULL PRIMARY KEY, user_auth_id NUMBER(19), approved NUMBER(1), redirect_uri VARCHAR2(2048), client_id VARCHAR2(256), CONSTRAINT approved_check CHECK (approved in (1,0)))
select u from DefaultUserInfo u WHERE u.preferredUsername = :
CREATE TABLE saved_user_auth ( id NUMBER(19) NOT NULL PRIMARY KEY, name VARCHAR2(1024), authenticated NUMBER(1), source_class VARCHAR2(2048), CONSTRAINT authenticated_check CHECK (authenticated in (1,0)))
CREATE TABLE IF NOT EXISTS client_default_acr_value (	owner_id BIGINT,	default_acr_value VARCHAR(2000))
CREATE TABLE IF NOT EXISTS permission_ticket (	id SERIAL PRIMARY KEY,	ticket VARCHAR(256) NOT NULL,	permission_id BIGINT NOT NULL,	expiration TIMESTAMP)
CREATE TABLE permission_scope ( owner_id NUMBER(19) NOT NULL, scope VARCHAR2(256) NOT NULL)
CREATE TABLE IF NOT EXISTS refresh_token (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	token_value VARCHAR(4096),	expiration TIMESTAMP NULL,	auth_holder_id BIGINT,	client_id BIGINT)
CREATE TABLE client_claims_redirect_uri ( owner_id NUMBER(19), redirect_uri VARCHAR2(2048))
CREATE TABLE permission ( id NUMBER(19) NOT NULL PRIMARY KEY, resource_set_id NUMBER(19))
CREATE TABLE IF NOT EXISTS refresh_token (	id SERIAL PRIMARY KEY,	token_value VARCHAR(4096),	expiration TIMESTAMP,	auth_holder_id BIGINT,	client_id BIGINT)
CREATE TABLE claim_to_policy ( policy_id NUMBER(19) NOT NULL, claim_id NUMBER(19) NOT NULL)
CREATE TABLE IF NOT EXISTS authentication_holder (	id SERIAL PRIMARY KEY,	user_auth_id BIGINT,	approved BOOLEAN,	redirect_uri VARCHAR(2048),	client_id VARCHAR(256))
select p from PairwiseIdentifier p
CREATE TABLE client_default_acr_value ( owner_id NUMBER(19), default_acr_value VARCHAR2(2000))
CREATE TABLE auth_holder_authority ( owner_id NUMBER(19), authority VARCHAR2(256))
CREATE TABLE resource_set ( id NUMBER(19) NOT NULL PRIMARY KEY, name VARCHAR2(1024) NOT NULL, uri VARCHAR2(1024), icon_uri VARCHAR2(1024), rs_type VARCHAR2(256), owner VARCHAR2(256) NOT NULL, client_id VARCHAR2(256))
CREATE TABLE IF NOT EXISTS claim_to_policy (	policy_id BIGINT NOT NULL,	claim_id BIGINT NOT NULL)
CREATE TABLE IF NOT EXISTS refresh_token (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	token_value VARCHAR(4096),	expiration TIMESTAMP,	auth_holder_id BIGINT,	client_id BIGINT)
CREATE TABLE IF NOT EXISTS whitelisted_site (	id SERIAL PRIMARY KEY,	creator_user_id VARCHAR(256),	client_id VARCHAR(256))
CREATE TABLE access_token_permissions ( access_token_id NUMBER(19) NOT NULL, permission_id NUMBER(19) NOT NULL)
CREATE TABLE IF NOT EXISTS client_request_uri (	owner_id BIGINT,	request_uri VARCHAR(2000))
CREATE TABLE client_scope ( owner_id NUMBER(19), scope VARCHAR2(2048))
create table IF NOT EXISTS users( username varchar(50) not null primary key, password varchar(50) not null, enabled boolean not null)
CREATE TABLE IF NOT EXISTS saved_registered_client (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	issuer VARCHAR(1024),	registered_client VARCHAR(8192))
CREATE INDEX cd_ci_idx ON client_details(client_id);
CREATE TABLE IF NOT EXISTS authentication_holder_extension (	owner_id BIGINT,	extension VARCHAR(2048),	val VARCHAR(2048))
CREATE INDEX ts_oi_idx ON token_scope(owner_id);
create table authorities ( username varchar2(50) not null, authority varchar2(50) not null, constraint fk_authorities_users foreign key(username) references users(username), constraint ix_authority unique (username,authority))
CREATE TABLE IF NOT EXISTS pairwise_identifier (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	identifier VARCHAR(256),	sub VARCHAR(256),	sector_identifier VARCHAR(2048))
CREATE TABLE auth_holder_extension ( owner_id NUMBER(19), extension VARCHAR2(2048), val VARCHAR2(2048))
CREATE TABLE IF NOT EXISTS address (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	formatted VARCHAR(256),	street_address VARCHAR(256),	locality VARCHAR(256),	region VARCHAR(256),	postal_code VARCHAR(256),	country VARCHAR(256))
CREATE TABLE auth_holder_resource_id ( owner_id NUMBER(19), resource_id VARCHAR2(2048))
CREATE TABLE IF NOT EXISTS pairwise_identifier (	id SERIAL PRIMARY KEY,	identifier VARCHAR(256),	sub VARCHAR(256),	sector_identifier VARCHAR(2048))
CREATE TABLE saved_registered_client ( id NUMBER(19) NOT NULL PRIMARY KEY, issuer VARCHAR2(1024), registered_client CLOB)
select r from ResourceSet r
select a from AuthenticationHolderEntity a
CREATE TABLE approved_site_scope ( owner_id NUMBER(19), scope VARCHAR2(256))
CREATE TABLE IF NOT EXISTS saved_user_auth (	id SERIAL PRIMARY KEY,	name VARCHAR(1024),	authenticated BOOLEAN,	source_class VARCHAR(2048))
CREATE TABLE IF NOT EXISTS whitelisted_site_scope (	owner_id BIGINT,	scope VARCHAR(256))
CREATE TABLE client_post_logout_redir_uri ( owner_id NUMBER(19), post_logout_redirect_uri VARCHAR2(2000))
CREATE TABLE IF NOT EXISTS authentication_holder (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	user_auth_id BIGINT,	approved BOOLEAN,	redirect_uri VARCHAR(2048),	client_id VARCHAR(256))
CREATE TABLE IF NOT EXISTS token_scope (	owner_id BIGINT,	scope VARCHAR(2048))
CREATE TABLE IF NOT EXISTS policy (	id SERIAL PRIMARY KEY,	name VARCHAR(1024),	resource_set_id BIGINT)
CREATE TABLE IF NOT EXISTS claim_issuer (	owner_id BIGINT NOT NULL,	issuer VARCHAR(1024))
CREATE TABLE IF NOT EXISTS system_scope (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	scope VARCHAR(256) NOT NULL,	description VARCHAR(4096),	icon VARCHAR(256),	restricted BOOLEAN DEFAULT false NOT NULL,	default_scope BOOLEAN DEFAULT false NOT NULL,	structured BOOLEAN DEFAULT false NOT NULL,	structured_param_description VARCHAR(256),	UNIQUE (scope))
select a from OAuth2AccessTokenEntity a where a.idToken = :
select w from WhitelistedSite w where w.creatorUserId = :
CREATE TABLE IF NOT EXISTS approved_site (	id SERIAL PRIMARY KEY,	user_id VARCHAR(256),	client_id VARCHAR(256),	creation_date TIMESTAMP,	access_date TIMESTAMP,	timeout_date TIMESTAMP,	whitelisted_site_id BIGINT)
select a from ApprovedSite a where a.userId = :
CREATE TABLE IF NOT EXISTS user_info (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	sub VARCHAR(256),	preferred_username VARCHAR(256),	name VARCHAR(256),	given_name VARCHAR(256),	family_name VARCHAR(256),	middle_name VARCHAR(256),	nickname VARCHAR(256),	profile VARCHAR(256),	picture VARCHAR(256),	website VARCHAR(256),	email VARCHAR(256),	email_verified BOOLEAN,	gender VARCHAR(256),	zone_info VARCHAR(256),	locale VARCHAR(256),	phone_number VARCHAR(256),	phone_number_verified BOOLEAN,	address_id VARCHAR(256),	updated_time VARCHAR(256),	birthdate VARCHAR(256),	src VARCHAR(4096))
CREATE TABLE IF NOT EXISTS client_grant_type (	owner_id BIGINT,	grant_type VARCHAR(2000))
select p from PermissionTicket p
CREATE TABLE token_scope ( owner_id NUMBER(19), scope VARCHAR2(2048))
select r from ResourceSet r where r.owner = :
CREATE TABLE IF NOT EXISTS resource_set_scope (	owner_id BIGINT NOT NULL,	scope VARCHAR(256) NOT NULL)
CREATE TABLE IF NOT EXISTS authorization_code (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	code VARCHAR(256),	auth_holder_id BIGINT,	expiration TIMESTAMP NULL)
select a from OAuth2AccessTokenEntity a
CREATE TABLE IF NOT EXISTS resource_set (	id SERIAL PRIMARY KEY,	name VARCHAR(1024) NOT NULL,	uri VARCHAR(1024),	icon_uri VARCHAR(1024),	rs_type VARCHAR(256),	owner VARCHAR(256) NOT NULL,	client_id VARCHAR(256))
SELECT c FROM ClientDetailsEntity c
CREATE TABLE IF NOT EXISTS access_token_permissions (	access_token_id BIGINT NOT NULL,	permission_id BIGINT NOT NULL)
CREATE TABLE IF NOT EXISTS client_contact (	owner_id BIGINT,	contact VARCHAR(256))
create table IF NOT EXISTS authorities ( username varchar(50) not null, authority varchar(50) not null, constraint fk_authorities_users foreign key(username) references users(username), constraint ix_authority unique (username,authority))
select r from OAuth2RefreshTokenEntity r
CREATE TABLE IF NOT EXISTS address (	id SERIAL PRIMARY KEY,	formatted VARCHAR(256),	street_address VARCHAR(256),	locality VARCHAR(256),	region VARCHAR(256),	postal_code VARCHAR(256),	country VARCHAR(256))
CREATE TABLE policy ( id NUMBER(19) NOT NULL PRIMARY KEY, name VARCHAR2(1024), resource_set_id NUMBER(19))
CREATE TABLE approved_site ( id NUMBER(19) NOT NULL PRIMARY KEY, user_id VARCHAR2(256), client_id VARCHAR2(256), creation_date TIMESTAMP, access_date TIMESTAMP, timeout_date TIMESTAMP, whitelisted_site_id NUMBER(19))
select p from PermissionTicket p where p.permission.resourceSet.id = :
CREATE TABLE claim_token_format ( owner_id NUMBER(19) NOT NULL, claim_token_format VARCHAR2(1024) NOT NULL)
CREATE TABLE IF NOT EXISTS access_token (	id SERIAL PRIMARY KEY,	token_value VARCHAR(4096),	expiration TIMESTAMP,	token_type VARCHAR(256),	refresh_token_id BIGINT,	client_id BIGINT,	auth_holder_id BIGINT,	id_token_id BIGINT,	approved_site_id BIGINT)
select r from OAuth2RefreshTokenEntity r where r.expiration <= :
CREATE TABLE IF NOT EXISTS client_resource (	owner_id BIGINT, 	resource_id VARCHAR(256) )
select p from PairwiseIdentifier p WHERE p.userSub = :" + PairwiseIdentifier.PARAM_SUB + " AND p.sectorIdentifier = :
CREATE TABLE IF NOT EXISTS permission_scope (	owner_id BIGINT NOT NULL,	scope VARCHAR(256) NOT NULL)
CREATE TABLE whitelisted_site_scope ( owner_id NUMBER(19), scope VARCHAR2(256))
CREATE TABLE IF NOT EXISTS permission (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	resource_set_id BIGINT)
CREATE TABLE claim ( id NUMBER(19) NOT NULL PRIMARY KEY, name VARCHAR2(256), friendly_name VARCHAR2(1024), claim_type VARCHAR2(1024), claim_value VARCHAR2(1024))
CREATE TABLE user_info ( id NUMBER(19) NOT NULL PRIMARY KEY, sub VARCHAR2(256), preferred_username VARCHAR2(256), name VARCHAR2(256), given_name VARCHAR2(256), family_name VARCHAR2(256), middle_name VARCHAR2(256), nickname VARCHAR2(256), profile VARCHAR2(256), picture VARCHAR2(256), website VARCHAR2(256), email VARCHAR2(256), email_verified NUMBER(1), gender VARCHAR2(256), zone_info VARCHAR2(256), locale VARCHAR2(256), phone_number VARCHAR2(256), phone_number_verified NUMBER(1), address_id VARCHAR2(256), updated_time VARCHAR2(256), birthdate VARCHAR2(256), src VARCHAR2(4000), CONSTRAINT email_verified_check CHECK (email_verified in (1,0)), CONSTRAINT phone_number_verified_check CHECK (phone_number_verified in (1,0)))
select a from ApprovedSite a
CREATE TABLE IF NOT EXISTS authentication_holder_authority (	owner_id BIGINT,	authority VARCHAR(256))
CREATE TABLE IF NOT EXISTS user_info (	id SERIAL PRIMARY KEY,	sub VARCHAR(256),	preferred_username VARCHAR(256),	name VARCHAR(256),	given_name VARCHAR(256),	family_name VARCHAR(256),	middle_name VARCHAR(256),	nickname VARCHAR(256),	profile VARCHAR(256),	picture VARCHAR(256),	website VARCHAR(256),	email VARCHAR(256),	email_verified BOOLEAN,	gender VARCHAR(256),	zone_info VARCHAR(256),	locale VARCHAR(256),	phone_number VARCHAR(256),	phone_number_verified BOOLEAN,	address_id VARCHAR(256),	updated_time VARCHAR(256),	birthdate VARCHAR(256),	src VARCHAR(4096))
select w from WhitelistedSite w
CREATE TABLE IF NOT EXISTS claim (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	name VARCHAR(256),	friendly_name VARCHAR(1024),	claim_type VARCHAR(1024),	claim_value VARCHAR(1024))
select c from ClientDetailsEntity c where c.clientId = :
CREATE TABLE saved_user_auth_authority ( owner_id NUMBER(19), authority VARCHAR2(256))
CREATE TABLE IF NOT EXISTS authentication_holder_request_parameter (	owner_id BIGINT,	param VARCHAR(2048),	val VARCHAR(2048))
select a from OAuth2AccessTokenEntity a where a.client = :
CREATE TABLE client_grant_type ( owner_id NUMBER(19), grant_type VARCHAR2(2000))
CREATE TABLE IF NOT EXISTS approved_site_scope (	owner_id BIGINT,	scope VARCHAR(256))
CREATE TABLE client_authority ( owner_id NUMBER(19), authority VARCHAR2(256))
CREATE TABLE IF NOT EXISTS policy (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	name VARCHAR(1024),	resource_set_id BIGINT)
CREATE TABLE IF NOT EXISTS permission (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	resource_set_id BIGINT)
CREATE TABLE IF NOT EXISTS claim_to_permission_ticket (	permission_ticket_id BIGINT NOT NULL,	claim_id BIGINT NOT NULL)
CREATE TABLE IF NOT EXISTS authorization_code (	id SERIAL PRIMARY KEY,	code VARCHAR(256),	auth_holder_id BIGINT,	expiration TIMESTAMP)
select r from OAuth2RefreshTokenEntity r where r.jwt = :
select a from AuthorizationCodeEntity a where a.code = :code
CREATE TABLE IF NOT EXISTS resource_set (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	name VARCHAR(1024) NOT NULL,	uri VARCHAR(1024),	icon_uri VARCHAR(1024),	rs_type VARCHAR(256),	owner VARCHAR(256) NOT NULL,	client_id VARCHAR(256))
select w from WhitelistedSite w where w.clientId = :
CREATE TABLE auth_holder_response_type ( owner_id NUMBER(19), response_type VARCHAR2(2048))
CREATE TABLE IF NOT EXISTS system_scope (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	scope VARCHAR(256) NOT NULL,	description VARCHAR(4096),	icon VARCHAR(256),	restricted BOOLEAN DEFAULT false NOT NULL,	default_scope BOOLEAN DEFAULT false NOT NULL,	structured BOOLEAN DEFAULT false NOT NULL,	structured_param_description VARCHAR(256),	UNIQUE (scope))
CREATE TABLE client_request_uri ( owner_id NUMBER(19), request_uri VARCHAR2(2000))
CREATE TABLE IF NOT EXISTS permission (	id SERIAL PRIMARY KEY,	resource_set_id BIGINT)
CREATE TABLE authentication_holder_scope ( owner_id NUMBER(19), scope VARCHAR2(2048))
CREATE TABLE IF NOT EXISTS claim_token_format (	owner_id BIGINT NOT NULL,	claim_token_format VARCHAR(1024))
select s from SystemScope s WHERE s.value = :
CREATE TABLE IF NOT EXISTS access_token (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	token_value VARCHAR(4096),	expiration TIMESTAMP NULL,	token_type VARCHAR(256),	refresh_token_id BIGINT,	client_id BIGINT,	auth_holder_id BIGINT,	id_token_id BIGINT,	approved_site_id BIGINT)
CREATE TABLE IF NOT EXISTS whitelisted_site (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	creator_user_id VARCHAR(256),	client_id VARCHAR(256))
select r from ResourceSet r where r.clientId = :
select a from ApprovedSite a where a.clientId = :" + ApprovedSite.PARAM_CLIENT_ID + " and a.userId = :
SELECT c from SavedRegisteredClient c
select a from OAuth2AccessTokenEntity a where a.expiration <= :
CREATE INDEX at_tv_idx ON access_token(token_value(767));
CREATE TABLE IF NOT EXISTS address (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	formatted VARCHAR(256),	street_address VARCHAR(256),	locality VARCHAR(256),	region VARCHAR(256),	postal_code VARCHAR(256),	country VARCHAR(256))
CREATE TABLE address ( id NUMBER(19) NOT NULL PRIMARY KEY, formatted VARCHAR2(256), street_address VARCHAR2(256), locality VARCHAR2(256), region VARCHAR2(256), postal_code VARCHAR2(256), country VARCHAR2(256))
CREATE TABLE IF NOT EXISTS authentication_holder (	id BIGINT AUTO_INCREMENT PRIMARY KEY,	user_auth_id BIGINT,	approved BOOLEAN,	redirect_uri VARCHAR(2048),	client_id VARCHAR(256))
CREATE TABLE refresh_token ( id NUMBER(19) NOT NULL PRIMARY KEY, token_value VARCHAR2(4000), expiration TIMESTAMP, auth_holder_id NUMBER(19), client_id NUMBER(19))
CREATE TABLE claim_to_permission_ticket ( permission_ticket_id NUMBER(19) NOT NULL, claim_id NUMBER(19) NOT NULL)
CREATE TABLE IF NOT EXISTS authentication_holder_response_type (	owner_id BIGINT,	response_type VARCHAR(2048))
CREATE TABLE IF NOT EXISTS permission_ticket (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	ticket VARCHAR(256) NOT NULL,	permission_id BIGINT NOT NULL,	expiration TIMESTAMP)
select a from OAuth2AccessTokenEntity a where a.approvedSite = :
CREATE TABLE authorization_code ( id NUMBER(19) NOT NULL PRIMARY KEY, code VARCHAR2(256), auth_holder_id NUMBER(19), expiration TIMESTAMP)
CREATE TABLE permission_ticket ( id NUMBER(19) NOT NULL PRIMARY KEY, ticket VARCHAR2(256) NOT NULL, permission_id NUMBER(19) NOT NULL, expiration TIMESTAMP)
CREATE TABLE IF NOT EXISTS client_response_type (	owner_id BIGINT,	response_type VARCHAR(2000))
CREATE TABLE auth_holder_request_parameter ( owner_id NUMBER(19), param VARCHAR2(2048), val VARCHAR2(2048))
CREATE TABLE IF NOT EXISTS client_scope (	owner_id BIGINT,	scope VARCHAR(2048))
CREATE TABLE IF NOT EXISTS claim (	id SERIAL PRIMARY KEY,	name VARCHAR(256),	friendly_name VARCHAR(1024),	claim_type VARCHAR(1024),	claim_value VARCHAR(1024))
select a from OAuth2AccessTokenEntity a join a.permissions p where p.resourceSet.id = :
CREATE TABLE IF NOT EXISTS saved_user_auth (	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,	name VARCHAR(1024),	authenticated BOOLEAN,	source_class VARCHAR(2048))
CREATE INDEX at_tv_idx ON access_token(token_value);
SELECT c from SavedRegisteredClient c where c.issuer = :issuer
CREATE TABLE IF NOT EXISTS blacklisted_site (	id SERIAL PRIMARY KEY,	uri VARCHAR(2048))
CREATE TABLE IF NOT EXISTS client_redirect_uri (	owner_id BIGINT, 	redirect_uri VARCHAR(2048) )
CREATE TABLE IF NOT EXISTS client_authority (	owner_id BIGINT,	authority VARCHAR(256))
create table users( username varchar2(50) not null primary key, password varchar2(50) not null, enabled number(1) not null, constraint enabled_check check (enabled in (1, 0)))
CREATE TABLE whitelisted_site ( id NUMBER(19) NOT NULL PRIMARY KEY, creator_user_id VARCHAR2(256), client_id VARCHAR2(256))
