CREATE TABLE ten (f1 INTEGER)
SELECT COUNT(*) FROM commit_table
SELECT * FROM huge_select
SELECT COUNT(*) FROM rollback_disconnect
select * from perf_test
INSERT INTO rollback_table VALUES (1)
select clientprocessid, clientinfo from SYSTEM.CONNECTIONS
SELECT 1 FROM DUAL WHERE FALSE
SELECT * FROM t
SELECT id, name FROM names where age > ? ORDER BY id
CREATE TABLE commit_table (f1 integer)
create table typetest (id integer GENERATED ALWAYS AS IDENTITY, time_col time, timestamp_col timestamp)
create table %sbooze (name varchar(20))
CREATE TABLE names ( id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(30) DEFAULT '' NOT NULL, age INTEGER DEFAULT 0 )
SELECT 1 FROM DUAL UNION ALL SELECT 2 FROM DUAL
INSERT INTO commit_table VALUES (1)
select * from typetest
select * from hockey
INSERT INTO autocommit_set VALUES (1)
select 1 from dual;
select count(*) from execute_ten_million_with_result_sets;
SELECT COUNT(*) FROM autocommit_set
select * from typetest order by id desc limit 1
INSERT INTO executemany_table VALUES (?, ?)
create table typetest (id integer GENERATED ALWAYS AS IDENTITY, date_col date)
SELECT 3 FROM DUAL UNION ALL SELECT 4 FROM DUAL
CREATE TABLE huge_select (f1 INTEGER GENERATED BY DEFAULT AS IDENTITY(s1))
CREATE TABLE t (x NUMERIC(%s,%s))
select * from executemany_table;
CREATE TABLE autocommit_set (f1 integer)
CREATE TABLE rollback_disconnect (f1 integer)
CREATE TABLE executemany_table (f1 INTEGER, f2 INTEGER)
SELECT 1 FROM DUAL
select name from %sbooze
select decimal_col from typetest order by id desc limit 1
CREATE TABLE rollback_table (f1 integer)
create table typetest (id integer GENERATED ALWAYS AS IDENTITY, binary_col binary(100000))
SELECT COUNT(*) FROM rollback_table
create table perf_test (a int,b char)
create table typetest (id integer GENERATED ALWAYS AS IDENTITY, timestamp_col timestamp)
CREATE TABLE execute_ten_million_with_result_sets (value INTEGER)
INSERT INTO ten VALUES (1)
SELECT * FROM executemany_table
INSERT INTO rollback_disconnect VALUES (1)
select 1 from dual
select number_col from typetest order by id desc limit 1
