select * from tests where test = 'testReusePreparedIndexedParameterStatement' and index < ?
SELECT * FROM keyspace.table
select count(*) from appointment where owner = '" + owner + "'
SELECT * FROM keyspace1.table2;
SELECT * FROM keyspace.table;", "arg1
SELECT * from keyspace.table;
select * from users
select * from table"));
SELECT e FROM TestEntity e WHERE e.creationDate BETWEEN :startTime AND :endTime
select * from table t"));
select * from users", "myClass
select * from /test this where /test.size > 1
select * from appointment where owner = 'Agim' and dateTime = '2009-06-01'
CREATE TABLE TestEntity ( id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1), creationDate TIMESTAMP NOT NULL, PRIMARY KEY(id))
INSERT INTO PERSON VALUES('Patrick', 'Linskey', 'OpenJPA', \ * '202 595 2064 x1111')
select * from table t where x"));
CREATE TABLE IF NOT EXISTS FUBAR(BAZ)
select * from tests where test = 'testReusePreparedMappedParameterStatement' and index < ?
SELECT * from keyspace.table
SELECT * FROM keyspace1.table1;
SELECT * FROM keyspace.table;
select * from appointment where owner = ? and dateTime = ?
select * from table t where x"));
select * from table t"));
select * from appointment where owner = ?
select * from table"));
create table Appointment (	id bigint generated by default as identity (start with 1), 						 	dateTime timestamp, 						 	notes varchar(255), 							owner varchar(255), 							ownerPhone varchar(255), 							pet varchar(255), 							primary key (id))
INSERT INTO PERSON VALUES('Patrick', 'Linskey', 'OpenJPA', \ * '202 595 2064 x1111')
select * from appointment where owner = 'Agim'
