CREATE TABLE PERSON ( id BIGINT GENERATED BY DEFAULT AS IDENTITY, first_name varchar(255) not null, last_name varchar(255) not null)
create table test (key_id int)
create table if not exists connection_info (id identity, connectionId UUID not null, connectionNumber int not null, url varchar not null, creationDate timestamp not null, connectionCreationDurationNanos bigInt, connectionProperties other)
select * from toto where param = cast(timestamp'2011-07-15 13:45:56.123' as DATE) /*DATE (non pure)*/
select * from test where key_id=2 /*setInt*/
select * from test where myDate=date'2013-02-28' /*setObject*/
select batched_stmt_order, filledSql from batched_statement_log where logId=? 
select * from test where myDate=? /*setObject*/
select 1 from statement_log where statement_log.connectionId=connection_info.connectionId)");
select * from test where key_id=123 /*setLong*/
select * from test where myTime=?
create table if not exists batched_statement_log (id identity, logId UUID not null, batched_stmt_order int not null, filledSql varchar not null)
select * from test where myString='hel''lo' /*setString*/
select * from test where myTimestamp=?
select * from test where myString=?
create table test (key_id int, myDate date, myTimestamp timestamp, myTime time, myBoolean boolean)
select count(*) from person
update statement_log set executionDurationNanos=?, nbRows=?, exception=?  where logId=?
update test set key_id=453  where key_id=876
create table test2 (key_id int)
select * from (select min(id) as ID, statementType, rawSql, count(1) as exec_count, 
select * from test where myDate=date'2011-01-02' /*setDate*/
select * from test;
create table if not exists statement_log (id identity, connectionId UUID not null, logId UUID not null, tstamp timestamp not null, statementType tinyInt not null, rawSql varchar not null, filledSql varchar not null, executionDurationNanos bigInt, fetchDurationNanos bigInt, rsetUsageDurationNanos bigInt, nbRows int, threadName varchar, exception varchar, timeout int, autoCommit boolean)
select * from test where myBoolean=true /*setBoolean*/
select * from test where myTime=time'15:23:43' /*setTime*/
select * from toto where name = 'toto$' /*VARCHAR*/ and age < 36 /*INTEGER*/
select sum(exec_plus_rset_usage_time) from v_statement_log
select * from test where key_id=1 /*setInt*/
select * from test
update test set key_id=453  where key_id=?
select * from test where myBoolean=?
select tstamp from statement_log order by tstamp desc limit 1 offset 
update statement_log set fetchDurationNanos=?, rsetUsageDurationNanos=?, nbRows=?  where logId=?
select * from toto where name = ?
create table test (key_id int, myDate date, myTimestamp timestamp(0), myTime time, myBoolean boolean, myString varchar(128))
select * from toto where param = date'2013-03-04' /*DATE*/
create table if not exists schema_version (version int not null)
create table test (key_id int)
create table test2 (key_id int)
select count(1) from statement_log
select version from schema_version
select * from (select min(id) as ID, statementType, rawSql, filledSql, count(1) as exec_count, 
select * from test where key_id=?
select * from test where myTimestamp=timestamp'2013-02-28 15:23:43.123' /*setTimestamp*/
select sum(exec_plus_rset_usage_time) from v_statement_log 
SELECT COUNT(*) from PERSON
select * from toto where name = ? and age < ?
select * from test where myDate=?
select * from toto where name = NULL /*VARCHAR*/
select * from toto where param = ?
select * from toto where param = NULL /*DATE*/
select * from toto where param = ? /*CLOB*/
select * from toto where param = timestamp'" + tstamp + "' /*TIMESTAMP*/
select * from test where myDate=date'2013-02-28' /*setDate*/
select * from test where myDate=date'2013-02-28' /*DATE*/
select * from toto where name = 'toto$' /*VARCHAR*/
select * from test where key_id=112 /*setByte*/
select * from test where myDate=cast(timestamp'2013-02-28 13:45:56.123' as DATE) /*setDate (non pure)*/
select logId from statement_log)");
